language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools # as per https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - platform-tools
    - build-tools-26.0.2
    - android-19
    - android-26
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
  licenses:
    - android-sdk-license-.+
    - google-gdk-license-.+

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew :skygear:build :skygear:check :skygear:connectedAndroidTest --stacktrace

before_deploy:
  - sudo pip install awscli
  - aws configure set preview.cloudfront true

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-SDK-Android
      all_branches: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "docs.skygear.io"
    skip_cleanup: true
    acl: public_read
    local_dir: "skygear/build/reports/androidTests/connected"
    upload-dir: "android/tests"
    cache_control: "max-age=604800"
    on:
      repo: SkygearIO/skygear-SDK-Android
      tags: true

env:
  global:
    - BINTRAY_USER="skygeario-builder"
    # BINTRAY_API_KEY
    - secure: "AA1JqW1GST/LEaaRCfdYmBPvMfoutSzSQlXOzTDOK/gccatphpW2vqf3KbA7ukDKpSwiIAVn4yttV/5MVQ8corvHXF5Vz5SqYfjM/g92JaKdP6DA4q5sAWzP86JhRqbuD12Vi9JvxlWbAWGcAF6CfMuXIeL09XdA0BQwm0D29+RyGkfv/Lit2aTBIcUWbhnOI3VF22lqwi9iwoJvMXkTzNcXQNSpViLjYhnsI/s0GFdqV45kLwY7ZeWzODG76sVJov9cIIegD8PKdO/wtO5HXBbDqsCC1GYSRQ7YmW1ec8VFBSghdb0IuQzh7mcCIauD0jTeRg4Kgz8Kj7sHvgrd4JUSv0kROSq+ANY0oX5W+S/WnvuT/IqluPCzfmDcv0Quyw4w2vSG/G8aVqXkX5eASbV9p4dMCnuM+PDdvQSKEA/jRCU0PatMRh30G3LdLn8NuNue8KBox36VTpZNYj0eIaoU8Sbab92iWnnEGS/LiAu1Th/dCSXHcKlRkOgI2GeggLnntOzqK/6VDhyrIyo9tWcNXRBNzWaqITPuER3Ryd2I218doPrOlDQAh+cOX1t7j8BPZTFeFRuEbLBcIQmN9IhjnczI6yBL7C0jLWu1RLOS9AQgcyV3CnpTBr5enBxCaLzJoUH4mDU4sEqdjtwnE996n87XI5HAF9DZNPhZSZw="
    # AWS_ACCESS_KEY_ID
    - secure: "dk3OKIEdLbTSUH60Z8Xrr1NVb6sip9wSShhSPFocUU4NVhGJPFn63CEHSsFfLEhj85P7YhZ3EwK7yP4pLJsEeMfiZvaYQGJZlCAK587tIo6h9xInDayGLyAfpn2WBxFIy/8BqHkluhrTVd2jgnqGvRI+Un3qFXhVfnU166kEcgGsnAqoopaHah3ZCkt4sTsSD8Ze+KrTNUWf1MeqsxIq7L1I0QHMfzGURCfMJ1p64Uo49nAQVGogwpJect0w7ryRZHhm1Q8rvDuFOLvBbSrmfTLiohoHEwPs7rGGRgkGfmRM+u/trBV3TpkyDt8wAcx+p3tmVxFdQmFO9FaA9ZF7llIOzqce+OjIq1Bp5moZwj2IEhjaRrGnY6PwPu7LJ1vtW6LoU8yhDK6mcfVj9hUaRwWbUPPnDuHqcABvMVTnzqad7uelGJ1vxnVSOP3UueeYYmEi+OQkRunaD8vL2cIKPmJA1YCRPhkPfjp3/KNNegVYZ8ICCIQnr9ahFiFcxgoWLXKkjoEejBGcfXzc5f6ShE/oaFQT7vMhTubTQesijcG3VD6+egXaS00m9SbAJ029bxoI+qR1MEEw/rBwIbjF7CpoG84z+xMxwsGsZSOUFKCtuwHblHDVrtNaMT0/A+dWH8IcqQ3zN7nF/wh3KW+sI1HCK1SvThfr7Y6gduc8yvo="
    # AWS_SECRET_ACCESS_KEY
    - secure: "JhKVnAZewlBfbGtYRpvrk/Bfc8KmLkJzOsGz/7agSLnsCrXeKvD7WkuAkoBn5goM/UJueqFz+rXui1VgFXUFWY5MtnbIlLPX3xKcKLi48cp6NPKpFvoyJzgeBtiqwgcNdm1bW9MBrZR+Dz6iL+TdRQWib/EvX3P30jVCkYIONHFYfe4lpAdTPCOzHnEzgdM9iDSoX/SVGimJdsezCCsRyiG1CT7D8/jDR0KTidp/0Ix8XdlJ/66g53u1w0OwZZpSKv+lyH+evQ4GoLiHLSETy0NYHAnTGmOjdOsVl2oqGlo1vrz3wWri+qujkUVOZhEDdMIdi6oMRugVxyALHCINObzp0OJkqWL68ijgLyzhc464qsN4KXmraQO4R+PCLQiV2EwXuZyTSExrB3DBiuP0AZgOi5RV6cE6AcvNkK7E8xaNtNQH9JUjHf0ndnfZ0mJFhfB1p0JPztaSET2Blz+V5hXBnxwl7s5Jj3zAOfaChuRxIoZswsD+bNp4M+9F/zm58Czj+Imrn0gbpX10EFg66TOllH83GrtoL2iMsOdrGkSNGMMQDQFvnbX1IG+SsnTSLY5huT0AxeN99r4wd7Ot8dhawRc2pqJD12eW+VSwfUMdV5gLmXzlMB7sJXLLCdoZ2Fgy3mvI9+/1Mj0KWJBg5m8NQ66zo/d8Ibop3iGWyGE="

notifications:
  slack:
    secure: "verBlT6aN1p/5HNUfShAOL5iaySB0n+SF+2IDlDXrdnJ1WCA+DYYnW7HHZPGTwoZ4YaEkjyDhQwB/1flj6y3yOuk/xgGgWIQiCeO9pZWnhdtHl8fS3Kr/g49VGrem/Nq0Pqm6f2YO2K33vioGHi3BV8blfs8vJdnYmQMRqzse+RQ7D1tfUn6FEYGQdBp4Xt/J2H0nsptsYzU7KHf1efcTHl7zS2kfMkaXXQnLN+H29AMILxn7b5//FxIm+bC6NZIjSOqiCBc4livcDOjjf8NS4utpsTXc0IIwx/6CqJcfRGpA/dLQJmPT5pJ8tSUthU2zcWqlfki2lpTi/CMja7wD8j9qGWCBkkmjX3fNblMOuJ21c62p+ikahsDTnzZ83kH+bIGG1IN9o7kL0Ksc9tocfn+HDzodOVAZt09p2YCzkAedqfm9eSMCSoXQzd6zzdWNzMXdiz7XXSfcZ5cVq7FPYwV+RrGwt0vbWZPEmNv8pvx5+bXjwwE+bms/1i///TZUZ1VYnzJ0u/Il/WsHGyjD7buQfqyxYHvqGd1Io1SXOVNHJ/pR0W1XJepQiY9c1za8YUyVgxVwncrqUFYgHGXbPSQJO09aTortYVHTq+icjTVJWBhKy5mB29LoGoR5JkJTCTdjvzbNFpCQin7D9toRNF3j79vB1PszArk7fvuzWM="
